var config = {}

config.domain = 'http://www.entrepreneur.com' ;
config.sites = ['http://www.entrepreneur.com/topic/sales',
                        'http://www.entrepreneur.com/topic/sales/2',
                        'http://www.entrepreneur.com/topic/sales/3',
                        'http://www.entrepreneur.com/topic/sales/4',
                        'http://www.entrepreneur.com/topic/sales/5',
                        'http://www.entrepreneur.com/topic/sales/6',
                        'http://www.entrepreneur.com/topic/sales/7',
                        'http://www.entrepreneur.com/topic/sales/8',
                        'http://www.entrepreneur.com/topic/sales/9',
                        'http://www.entrepreneur.com/topic/sales/10',
                        'http://www.entrepreneur.com/topic/sales/11',
                        'http://www.entrepreneur.com/topic/sales/12',
                        'http://www.entrepreneur.com/topic/sales/13',
                        'http://www.entrepreneur.com/topic/sales/14',
                        'http://www.entrepreneur.com/topic/sales/15',
                        'http://www.entrepreneur.com/topic/sales/16',
                        'http://www.entrepreneur.com/topic/sales/17',
                        'http://www.entrepreneur.com/topic/sales/18',
                        'http://www.entrepreneur.com/topic/sales/19',
                        'http://www.entrepreneur.com/topic/sales/20',
                        'http://www.entrepreneur.com/topic/sales/21',
                        'http://www.entrepreneur.com/topic/sales/22',
                        'http://www.entrepreneur.com/topic/sales/23',
                        'http://www.entrepreneur.com/topic/sales/24',
                        'http://www.entrepreneur.com/topic/sales/25',
                        'http://www.entrepreneur.com/topic/sales/26',
                        'http://www.entrepreneur.com/topic/sales/27',
                        'http://www.entrepreneur.com/topic/sales/28',
                        'http://www.entrepreneur.com/topic/sales/29',
                        'http://www.entrepreneur.com/topic/sales/30',
                        'http://www.entrepreneur.com/topic/sales/31',
                        'http://www.entrepreneur.com/topic/sales/32',
                        'http://www.entrepreneur.com/topic/sales/33',
                        'http://www.entrepreneur.com/topic/sales/34',
                        'http://www.entrepreneur.com/topic/sales/35',
                        'http://www.entrepreneur.com/topic/sales/36',
                        'http://www.entrepreneur.com/topic/sales/37',
                        'http://www.entrepreneur.com/topic/sales/38',
                        'http://www.entrepreneur.com/topic/sales/39',
                        'http://www.entrepreneur.com/topic/sales/40',
                        'http://www.entrepreneur.com/topic/sales/41',
                        'http://www.entrepreneur.com/topic/sales/42',
                        'http://www.entrepreneur.com/topic/sales/43',
                        'http://www.entrepreneur.com/topic/sales/44',
                        'http://www.entrepreneur.com/topic/sales/45',
                        'http://www.entrepreneur.com/topic/sales/46',
                        'http://www.entrepreneur.com/topic/sales/47',
                        'http://www.entrepreneur.com/topic/sales/48',
                        'http://www.entrepreneur.com/topic/sales/49'
                       ]  ;
config.next = 10 ;  // days to next domain scrape

module.exports = config ;
